# Generated by Django 5.1.3 on 2024-11-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_rename_chapters_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='attachment',
            field=models.URLField(blank=True, null=True),
        ),
    ]
