# Generated by Django 5.1.3 on 2024-11-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_chapter_attachment_type_alter_chapter_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('pdf', 'pdf'), ('img', 'image'), ('mp4', 'mp4'), ('ppt', 'ppt')], max_length=20, null=True),
        ),
    ]
